In [2]:
from __future__ import annotations
import re
from typing import Any, Dict, List, Optional, Tuple
import pandas as pd
import numpy as np

def stage_to_idx(task: str, stage: Any) -> Optional[int]:
    if pd.isna(stage):
        return None
 
    s = stage.strip().upper()
    if task.lower() == "t":
        m = re.match(r"^T\s*([1-4])", s)
        if not m:
            return None
        return int(m.group(1)) - 1
    elif task.lower() == "n":
        m = re.match(r"^N\s*([0-3])", s)
        if not m:
            return None
        return int(m.group(1))
    return None


def extract_ground_truth(df: pd.DataFrame, task: str) -> Optional[pd.Series]:
    if task == "t":
        return df["T14"].astype(int)
    elif task == "n":
        return df["N03"].astype(int)
    return None


def macro_prf(y_true: List[int], y_pred: List[int], num_classes: int) -> Tuple[float, float, float]:
    import numpy as np  # local
    K = num_classes
    tp = np.zeros(K, dtype=int)
    fp = np.zeros(K, dtype=int)
    fn = np.zeros(K, dtype=int)

    for yt, yp in zip(y_true, y_pred):
        if yp == yt:
            tp[yt] += 1
        else:
            fp[yp] += 1
            fn[yt] += 1

    def safe_div(a: float, b: float) -> float:
        return a / b if b > 0 else 0.0

    precs = []
    recs = []
    f1s = []
    for k in range(K):
        p = safe_div(tp[k], tp[k] + fp[k])
        r = safe_div(tp[k], tp[k] + fn[k])
        f1 = (2 * p * r / (p + r)) if (p + r) > 0 else 0.0
        precs.append(p)
        recs.append(r)
        f1s.append(f1)

    return float(sum(precs)) / K, float(sum(recs)) / K, float(sum(f1s)) / K

def pred_contains_groundtruth(task: str, pred_text, y_true_idx: int) -> bool:
    """GT 토큰(Tk/Nk)이 예측 문자열 어디에든 '부분 일치'로 포함되어 있으면 True."""
    if pd.isna(pred_text):
        return False
    s = str(pred_text)

    if task.lower() == "t":
        k = y_true_idx + 1  # 0->T1, 1->T2, ...
        pat = re.compile(rf"T\s*{k}(?:\s*[A-D])?(?!\s*\d)", re.IGNORECASE)
    else:
        k = y_true_idx      # 0->N0, 1->N1, ...
        pat = re.compile(rf"N\s*{k}(?:\s*[A-D])?(?!\s*\d)", re.IGNORECASE)

    return bool(pat.search(s))

In [3]:
from pathlib import Path
import re
import pandas as pd

# "__kewltm__t__"처럼 이중 밑줄 구분자를 기준으로 방법론/태스크만 캡처
PAT = re.compile(r"__(?P<method>[a-z0-9]+)__(?P<task>[tn])__")

def tcga_from_filename(path: Path):
    m = PAT.search(path.name)  # 파일명 어디에 있어도 찾음
    if not m:
        raise ValueError(f"Unexpected filename: {path.name}")
    return m.group("method"), m.group("task")

per_cancer_dir = Path("/home/yl3427/cylab/selfCorrectionAgent/runs")
for path in sorted(per_cancer_dir.glob("*.csv")):
    if path.name.startswith("manifest"):
        continue  
    df = pd.read_csv(path)
    cancer_type = path.stem.split("_")[0]
    method, task = tcga_from_filename(path)
    print(f"cancer_type: {cancer_type}, method: {method}, task: {task}")
    if method == "kewltm":
        df = df[~df["is_train"]]
    if task == "t":
        true_col = df["T14"]
    else:
        true_col = df["N03"]
    pred_col = df[f"{method}_stage"]
    pred_col = [stage_to_idx(task, stage) if stage else None for stage in pred_col]
    print(len(true_col), len([v for v in pred_col if v is not None]))

cancer_type: ACC, method: kewltm, task: n
84 25
cancer_type: ACC, method: kewltm, task: t
84 82
cancer_type: ACC, method: kewrag, task: n
88 48
cancer_type: ACC, method: kewrag, task: t
88 84
cancer_type: ACC, method: rag, task: n
88 40
cancer_type: ACC, method: rag, task: t
88 80
cancer_type: ACC, method: zscot, task: n
88 75
cancer_type: ACC, method: zscot, task: t
88 83
cancer_type: BLCA, method: kewltm, task: n
321 310
cancer_type: BLCA, method: kewltm, task: t
328 321
cancer_type: BLCA, method: kewrag, task: n
338 304
cancer_type: BLCA, method: kewrag, task: t
345 336
cancer_type: BLCA, method: rag, task: n
338 299
cancer_type: BLCA, method: rag, task: t
345 317
cancer_type: BLCA, method: zscot, task: n
338 315
cancer_type: BLCA, method: zscot, task: t
345 332
cancer_type: BRCA, method: kewltm, task: n
760 571
cancer_type: BRCA, method: kewltm, task: t
979 952
cancer_type: BRCA, method: kewrag, task: n
800 729
cancer_type: BRCA, method: kewrag, task: t
1031 983
cancer_type: BRCA, method: rag, task: n
800 708
cancer_type: BRCA, method: rag, task: t
1031 986
cancer_type: BRCA, method: zscot, task: n
800 762
cancer_type: BRCA, method: zscot, task: t
1031 1002
cancer_type: CESC, method: kewltm, task: n
175 168
cancer_type: CESC, method: kewltm, task: t
216 184
cancer_type: CESC, method: kewrag, task: n
184 178
cancer_type: CESC, method: kewrag, task: t
227 189
cancer_type: CESC, method: rag, task: n
184 158
cancer_type: CESC, method: rag, task: t
227 204
cancer_type: CESC, method: zscot, task: n
184 160
cancer_type: CESC, method: zscot, task: t
227 186
cancer_type: CHOL, method: kewltm, task: n
36 27
cancer_type: CHOL, method: kewltm, task: t
41 41
cancer_type: CHOL, method: kewrag, task: n
38 33
cancer_type: CHOL, method: kewrag, task: t
43 40
cancer_type: CHOL, method: rag, task: n
38 25
cancer_type: CHOL, method: rag, task: t
43 41
cancer_type: CHOL, method: zscot, task: n
38 33
cancer_type: CHOL, method: zscot, task: t
43 40
cancer_type: COAD, method: kewltm, task: n
397 381
cancer_type: COAD, method: kewltm, task: t
396 374
cancer_type: COAD, method: kewrag, task: n
418 406
cancer_type: COAD, method: kewrag, task: t
417 405
cancer_type: COAD, method: rag, task: n
418 391
cancer_type: COAD, method: rag, task: t
417 373
cancer_type: COAD, method: zscot, task: n
418 406
cancer_type: COAD, method: zscot, task: t
417 402
cancer_type: ESCA, method: kewltm, task: n
122 118
cancer_type: ESCA, method: kewltm, task: t
123 119
cancer_type: ESCA, method: kewrag, task: n
128 123
cancer_type: ESCA, method: kewrag, task: t
129 122
cancer_type: ESCA, method: rag, task: n
128 123
cancer_type: ESCA, method: rag, task: t
129 116
cancer_type: ESCA, method: zscot, task: n
128 120
cancer_type: ESCA, method: zscot, task: t
129 122
cancer_type: HNSC, method: kewltm, task: n
399 384
cancer_type: HNSC, method: kewltm, task: t
434 429
cancer_type: HNSC, method: kewrag, task: n
420 375
cancer_type: HNSC, method: kewrag, task: t
457 422
cancer_type: HNSC, method: rag, task: n
420 381
cancer_type: HNSC, method: rag, task: t
457 412
cancer_type: HNSC, method: zscot, task: n
420 396
cancer_type: HNSC, method: zscot, task: t
457 438
cancer_type: KICH, method: kewltm, task: n
50 28
cancer_type: KICH, method: kewltm, task: t
106 100
cancer_type: KICH, method: kewrag, task: n
53 52
cancer_type: KICH, method: kewrag, task: t
112 88
cancer_type: KICH, method: rag, task: n
53 38
cancer_type: KICH, method: rag, task: t
112 101
cancer_type: KICH, method: zscot, task: n
53 50
cancer_type: KICH, method: zscot, task: t
112 108
cancer_type: KIRC, method: kewltm, task: n
238 193
cancer_type: KIRC, method: kewltm, task: t
499 490
cancer_type: KIRC, method: kewrag, task: n
251 170
cancer_type: KIRC, method: kewrag, task: t
525 507
cancer_type: KIRC, method: rag, task: n
251 147
cancer_type: KIRC, method: rag, task: t
525 487
cancer_type: KIRC, method: zscot, task: n
251 196
cancer_type: KIRC, method: zscot, task: t
525 504
cancer_type: KIRP, method: kewltm, task: n
70 62
cancer_type: KIRP, method: kewltm, task: t
266 261
cancer_type: KIRP, method: kewrag, task: n
74 58
cancer_type: KIRP, method: kewrag, task: t
280 271
cancer_type: KIRP, method: rag, task: n
74 56
cancer_type: KIRP, method: rag, task: t
280 259
cancer_type: KIRP, method: zscot, task: n
74 63
cancer_type: KIRP, method: zscot, task: t
280 274
cancer_type: LIHC, method: kewltm, task: n
217 50
cancer_type: LIHC, method: kewltm, task: t
322 283
cancer_type: LIHC, method: kewrag, task: n
228 173
cancer_type: LIHC, method: kewrag, task: t
339 322
cancer_type: LIHC, method: rag, task: n
228 134
cancer_type: LIHC, method: rag, task: t
339 307
cancer_type: LIHC, method: zscot, task: n
228 193
cancer_type: LIHC, method: zscot, task: t
339 327
cancer_type: LUAD, method: kewltm, task: n
453 425
cancer_type: LUAD, method: kewltm, task: t
462 447
cancer_type: LUAD, method: kewrag, task: n
477 465
cancer_type: LUAD, method: kewrag, task: t
486 457
cancer_type: LUAD, method: rag, task: n
477 431
cancer_type: LUAD, method: rag, task: t
486 437
cancer_type: LUAD, method: zscot, task: n
477 438
cancer_type: LUAD, method: zscot, task: t
486 468
cancer_type: LUSC, method: kewltm, task: n
439 388
cancer_type: LUSC, method: kewltm, task: t
445 429
cancer_type: LUSC, method: kewrag, task: n
462 429
cancer_type: LUSC, method: kewrag, task: t
468 436
cancer_type: LUSC, method: rag, task: n
462 407
cancer_type: LUSC, method: rag, task: t
468 442
cancer_type: LUSC, method: zscot, task: n
462 419
cancer_type: LUSC, method: zscot, task: t
468 451
cancer_type: MESO, method: kewltm, task: n
71 38
cancer_type: MESO, method: kewltm, task: t
74 61
cancer_type: MESO, method: kewrag, task: n
75 65
cancer_type: MESO, method: kewrag, task: t
78 66
cancer_type: MESO, method: rag, task: n
75 55
cancer_type: MESO, method: rag, task: t
78 63
cancer_type: MESO, method: zscot, task: n
75 58
cancer_type: MESO, method: zscot, task: t
78 67
cancer_type: PAAD, method: kewltm, task: n
162 161
cancer_type: PAAD, method: kewltm, task: t
165 164
cancer_type: PAAD, method: kewrag, task: n
171 164
cancer_type: PAAD, method: kewrag, task: t
174 146
cancer_type: PAAD, method: rag, task: n
171 136
cancer_type: PAAD, method: rag, task: t
174 162
cancer_type: PAAD, method: zscot, task: n
171 164
cancer_type: PAAD, method: zscot, task: t
174 166
cancer_type: PRAD, method: kewltm, task: n
359 353
cancer_type: PRAD, method: kewltm, task: t
417 408
cancer_type: PRAD, method: kewrag, task: n
378 370
cancer_type: PRAD, method: kewrag, task: t
439 344
cancer_type: PRAD, method: rag, task: n
378 340
cancer_type: PRAD, method: rag, task: t
439 390
cancer_type: PRAD, method: zscot, task: n
378 364
cancer_type: PRAD, method: zscot, task: t
439 416
cancer_type: READ, method: kewltm, task: n
152 151
cancer_type: READ, method: kewltm, task: t
154 150
cancer_type: READ, method: kewrag, task: n
160 152
cancer_type: READ, method: kewrag, task: t
162 134
cancer_type: READ, method: rag, task: n
160 139
cancer_type: READ, method: rag, task: t
162 149
cancer_type: READ, method: zscot, task: n
160 152
cancer_type: READ, method: zscot, task: t
162 154
cancer_type: SKCM, method: kewltm, task: n
82 76
cancer_type: SKCM, method: kewltm, task: t
95 92
cancer_type: SKCM, method: kewrag, task: n
86 75
cancer_type: SKCM, method: kewrag, task: t
100 90
cancer_type: SKCM, method: rag, task: n
86 57
cancer_type: SKCM, method: rag, task: t
100 87
cancer_type: SKCM, method: zscot, task: n
86 74
cancer_type: SKCM, method: zscot, task: t
100 89
cancer_type: STAD, method: kewltm, task: n
326 315
cancer_type: STAD, method: kewltm, task: t
333 327
cancer_type: STAD, method: kewrag, task: n
343 336
cancer_type: STAD, method: kewrag, task: t
351 330
cancer_type: STAD, method: rag, task: n
343 314
cancer_type: STAD, method: rag, task: t
351 320
cancer_type: STAD, method: zscot, task: n
343 328
cancer_type: STAD, method: zscot, task: t
351 337
cancer_type: TGCT, method: kewltm, task: n
30 25
cancer_type: TGCT, method: kewltm, task: t
82 81
cancer_type: TGCT, method: kewrag, task: n
32 22
cancer_type: TGCT, method: kewrag, task: t
86 80
cancer_type: TGCT, method: rag, task: n
32 21
cancer_type: TGCT, method: rag, task: t
86 76
cancer_type: TGCT, method: zscot, task: n
32 30
cancer_type: TGCT, method: zscot, task: t
86 81
cancer_type: THCA, method: kewltm, task: n
415 397
cancer_type: THCA, method: kewltm, task: t
461 447
cancer_type: THCA, method: kewrag, task: n
437 383
cancer_type: THCA, method: kewrag, task: t
485 474
cancer_type: THCA, method: rag, task: n
437 384
cancer_type: THCA, method: rag, task: t
485 465
cancer_type: THCA, method: zscot, task: n
437 417
cancer_type: THCA, method: zscot, task: t
485 478
cancer_type: UVM, method: kewltm, task: n
35 35
cancer_type: UVM, method: kewltm, task: t
62 61
cancer_type: UVM, method: kewrag, task: n
37 22
cancer_type: UVM, method: kewrag, task: t
65 64
cancer_type: UVM, method: rag, task: n
37 23
cancer_type: UVM, method: rag, task: t
65 63
cancer_type: UVM, method: zscot, task: n
37 36
cancer_type: UVM, method: zscot, task: t
65 64

In [4]:
per_cancer_dir = Path("/home/yl3427/cylab/selfCorrectionAgent/runs2")
for path in sorted(per_cancer_dir.glob("*.csv")):
    if path.name.startswith("manifest"):
        continue  
    df = pd.read_csv(path)
    cancer_type = path.stem.split("_")[0]
    method, task = tcga_from_filename(path)
    print(f"cancer_type: {cancer_type}, method: {method}, task: {task}")
    if method == "kewltm":
        df = df[~df["is_train"]]
    if task == "t":
        true_col = df["T14"]
    else:
        true_col = df["N03"]
    pred_col = df[f"{method}_stage"]
    pred_col = [stage_to_idx(task, stage) if stage else None for stage in pred_col]
    print(len(true_col), len([v for v in pred_col if v is not None]))

cancer_type: ACC, method: kewltm, task: n
84 28

cancer_type: ACC, method: kewltm, task: t
84 84
cancer_type: ACC, method: kewrag, task: n
88 60
cancer_type: ACC, method: kewrag, task: t
88 85
cancer_type: ACC, method: rag, task: n
88 59
cancer_type: ACC, method: rag, task: t
88 85
cancer_type: ACC, method: zscot, task: n
88 80
cancer_type: ACC, method: zscot, task: t
88 86
cancer_type: BLCA, method: kewltm, task: n
321 320
cancer_type: BLCA, method: kewltm, task: t
328 326
cancer_type: BLCA, method: kewrag, task: n
338 314
cancer_type: BLCA, method: kewrag, task: t
345 342
cancer_type: BLCA, method: rag, task: n
338 327
cancer_type: BLCA, method: rag, task: t
345 332
cancer_type: BLCA, method: zscot, task: n
338 329
cancer_type: BLCA, method: zscot, task: t
345 341
cancer_type: BRCA, method: kewltm, task: n
760 681
cancer_type: BRCA, method: kewltm, task: t
979 964
cancer_type: BRCA, method: kewrag, task: n
800 772
cancer_type: BRCA, method: kewrag, task: t
1031 1013
cancer_type: BRCA, method: rag, task: n
800 768
cancer_type: BRCA, method: rag, task: t
1031 1008
cancer_type: BRCA, method: zscot, task: n
800 785
cancer_type: BRCA, method: zscot, task: t
1031 1018
cancer_type: CESC, method: kewltm, task: n
175 172
cancer_type: CESC, method: kewltm, task: t
216 192
cancer_type: CESC, method: kewrag, task: n
184 183
cancer_type: CESC, method: kewrag, task: t
227 199
cancer_type: CESC, method: rag, task: n
184 178
cancer_type: CESC, method: rag, task: t
227 208
cancer_type: CESC, method: zscot, task: n
184 174
cancer_type: CESC, method: zscot, task: t
227 204
cancer_type: CHOL, method: kewltm, task: n
36 32
cancer_type: CHOL, method: kewltm, task: t
41 41
cancer_type: CHOL, method: kewrag, task: n
38 35
cancer_type: CHOL, method: kewrag, task: t
43 42
cancer_type: CHOL, method: rag, task: n
38 35
cancer_type: CHOL, method: rag, task: t
43 42
cancer_type: CHOL, method: zscot, task: n
38 38
cancer_type: CHOL, method: zscot, task: t
43 43
cancer_type: COAD, method: kewltm, task: n
397 391
cancer_type: COAD, method: kewltm, task: t
396 393
cancer_type: COAD, method: kewrag, task: n
418 412
cancer_type: COAD, method: kewrag, task: t
417 412
cancer_type: COAD, method: rag, task: n
418 410
cancer_type: COAD, method: rag, task: t
417 402
cancer_type: COAD, method: zscot, task: n
418 410
cancer_type: COAD, method: zscot, task: t
417 403
cancer_type: ESCA, method: kewltm, task: n
122 118
cancer_type: ESCA, method: kewltm, task: t
123 121
cancer_type: ESCA, method: kewrag, task: n
128 123
cancer_type: ESCA, method: kewrag, task: t
129 126
cancer_type: ESCA, method: rag, task: n
128 124
cancer_type: ESCA, method: rag, task: t
129 117
cancer_type: ESCA, method: zscot, task: n
128 127
cancer_type: ESCA, method: zscot, task: t
129 125
cancer_type: HNSC, method: kewltm, task: n
399 392
cancer_type: HNSC, method: kewltm, task: t
434 430
cancer_type: HNSC, method: kewrag, task: n
420 402
cancer_type: HNSC, method: kewrag, task: t
457 447
cancer_type: HNSC, method: rag, task: n
420 397
cancer_type: HNSC, method: rag, task: t
457 419
cancer_type: HNSC, method: zscot, task: n
420 405
cancer_type: HNSC, method: zscot, task: t
457 442
cancer_type: KICH, method: kewltm, task: n
50 40
cancer_type: KICH, method: kewltm, task: t
106 101
cancer_type: KICH, method: kewrag, task: n
53 53
cancer_type: KICH, method: kewrag, task: t
112 110
cancer_type: KICH, method: rag, task: n
53 41
cancer_type: KICH, method: rag, task: t
112 104
cancer_type: KICH, method: zscot, task: n
53 52
cancer_type: KICH, method: zscot, task: t
112 110
cancer_type: KIRC, method: kewltm, task: n
238 220
cancer_type: KIRC, method: kewltm, task: t
499 496
cancer_type: KIRC, method: kewrag, task: n
251 206
cancer_type: KIRC, method: kewrag, task: t
525 520
cancer_type: KIRC, method: rag, task: n
251 170
cancer_type: KIRC, method: rag, task: t
525 496
cancer_type: KIRC, method: zscot, task: n
251 223
cancer_type: KIRC, method: zscot, task: t
525 508
cancer_type: KIRP, method: kewltm, task: n
70 69
cancer_type: KIRP, method: kewltm, task: t
266 264
cancer_type: KIRP, method: kewrag, task: n
74 68
cancer_type: KIRP, method: kewrag, task: t
280 277
cancer_type: KIRP, method: rag, task: n
74 62
cancer_type: KIRP, method: rag, task: t
280 263
cancer_type: KIRP, method: zscot, task: n
74 69
cancer_type: KIRP, method: zscot, task: t
280 274
cancer_type: LIHC, method: kewltm, task: n
217 73
cancer_type: LIHC, method: kewltm, task: t
322 303
cancer_type: LIHC, method: kewrag, task: n
228 205
cancer_type: LIHC, method: kewrag, task: t
339 332
cancer_type: LIHC, method: rag, task: n
228 154
cancer_type: LIHC, method: rag, task: t
339 318
cancer_type: LIHC, method: zscot, task: n
228 213
cancer_type: LIHC, method: zscot, task: t
339 329
cancer_type: LUAD, method: kewltm, task: n
453 443
cancer_type: LUAD, method: kewltm, task: t
462 455
cancer_type: LUAD, method: kewrag, task: n
477 473
cancer_type: LUAD, method: kewrag, task: t
486 480
cancer_type: LUAD, method: rag, task: n
477 445
cancer_type: LUAD, method: rag, task: t
486 444
cancer_type: LUAD, method: zscot, task: n
477 443
cancer_type: LUAD, method: zscot, task: t
486 471
cancer_type: LUSC, method: kewltm, task: n
439 424
cancer_type: LUSC, method: kewltm, task: t
445 439
cancer_type: LUSC, method: kewrag, task: n
462 443
cancer_type: LUSC, method: kewrag, task: t
468 457
cancer_type: LUSC, method: rag, task: n
462 428
cancer_type: LUSC, method: rag, task: t
468 450
cancer_type: LUSC, method: zscot, task: n
462 432
cancer_type: LUSC, method: zscot, task: t
468 458
cancer_type: MESO, method: kewltm, task: n
71 42
cancer_type: MESO, method: kewltm, task: t
74 69
cancer_type: MESO, method: kewrag, task: n
75 69
cancer_type: MESO, method: kewrag, task: t
78 73
cancer_type: MESO, method: rag, task: n
75 65
cancer_type: MESO, method: rag, task: t
78 70
cancer_type: MESO, method: zscot, task: n
75 66
cancer_type: MESO, method: zscot, task: t
78 72
cancer_type: PAAD, method: kewltm, task: n
162 161
cancer_type: PAAD, method: kewltm, task: t
165 165
cancer_type: PAAD, method: kewrag, task: n
171 167
cancer_type: PAAD, method: kewrag, task: t
174 171
cancer_type: PAAD, method: rag, task: n
171 141
cancer_type: PAAD, method: rag, task: t
174 165
cancer_type: PAAD, method: zscot, task: n
171 169
cancer_type: PAAD, method: zscot, task: t
174 169
cancer_type: PRAD, method: kewltm, task: n
359 357
cancer_type: PRAD, method: kewltm, task: t
417 412
cancer_type: PRAD, method: kewrag, task: n
378 373
cancer_type: PRAD, method: kewrag, task: t
439 430
cancer_type: PRAD, method: rag, task: n
378 342
cancer_type: PRAD, method: rag, task: t
439 398
cancer_type: PRAD, method: zscot, task: n
378 370
cancer_type: PRAD, method: zscot, task: t
439 421
cancer_type: READ, method: kewltm, task: n
152 152
cancer_type: READ, method: kewltm, task: t
154 150
cancer_type: READ, method: kewrag, task: n
160 156
cancer_type: READ, method: kewrag, task: t
162 141
cancer_type: READ, method: rag, task: n
160 144
cancer_type: READ, method: rag, task: t
162 150
cancer_type: READ, method: zscot, task: n
160 155
cancer_type: READ, method: zscot, task: t
162 156
cancer_type: SKCM, method: kewltm, task: n
82 80
cancer_type: SKCM, method: kewltm, task: t
95 93
cancer_type: SKCM, method: kewrag, task: n
86 85
cancer_type: SKCM, method: kewrag, task: t
100 98
cancer_type: SKCM, method: rag, task: n
86 67
cancer_type: SKCM, method: rag, task: t
100 89
cancer_type: SKCM, method: zscot, task: n
86 83
cancer_type: SKCM, method: zscot, task: t
100 93
cancer_type: STAD, method: kewltm, task: n
326 325
cancer_type: STAD, method: kewltm, task: t
333 331
cancer_type: STAD, method: kewrag, task: n
343 340
cancer_type: STAD, method: kewrag, task: t
351 337
cancer_type: STAD, method: rag, task: n
343 318
cancer_type: STAD, method: rag, task: t
351 323
cancer_type: STAD, method: zscot, task: n
343 339
cancer_type: STAD, method: zscot, task: t
351 339
cancer_type: TGCT, method: kewltm, task: n
30 28
cancer_type: TGCT, method: kewltm, task: t
82 81
cancer_type: TGCT, method: kewrag, task: n
32 31
cancer_type: TGCT, method: kewrag, task: t
86 84
cancer_type: TGCT, method: rag, task: n
32 27
cancer_type: TGCT, method: rag, task: t
86 76
cancer_type: TGCT, method: zscot, task: n
32 31
cancer_type: TGCT, method: zscot, task: t
86 85
cancer_type: THCA, method: kewltm, task: n
415 404
cancer_type: THCA, method: kewltm, task: t
461 457
cancer_type: THCA, method: kewrag, task: n
437 405
cancer_type: THCA, method: kewrag, task: t
485 482
cancer_type: THCA, method: rag, task: n
437 405
cancer_type: THCA, method: rag, task: t
485 468
cancer_type: THCA, method: zscot, task: n
437 425
cancer_type: THCA, method: zscot, task: t
485 478
cancer_type: UVM, method: kewltm, task: n
35 35
cancer_type: UVM, method: kewltm, task: t
62 61
cancer_type: UVM, method: kewrag, task: n
37 28
cancer_type: UVM, method: kewrag, task: t
65 64
cancer_type: UVM, method: rag, task: n
37 26
cancer_type: UVM, method: rag, task: t
65 64
cancer_type: UVM, method: zscot, task: n
37 36
cancer_type: UVM, method: zscot, task: t
65 65

In [5]:

per_cancer_dir = Path("/home/yl3427/cylab/selfCorrectionAgent/runs3")
for path in sorted(per_cancer_dir.glob("*.csv")):
    if path.name.startswith("manifest"):
        continue  
    df = pd.read_csv(path)
    cancer_type = path.stem.split("_")[0]
    method, task = tcga_from_filename(path)
    print(f"cancer_type: {cancer_type}, method: {method}, task: {task}")
    if method == "kewltm":
        df = df[~df["is_train"]]
    if task == "t":
        true_col = df["T14"]
    else:
        true_col = df["N03"]
    pred_col = df[f"{method}_stage"]
    pred_col = [stage_to_idx(task, stage) if stage else None for stage in pred_col]
    print(len([v for v in true_col if v is not None]), len([v for v in pred_col if v is not None]))

cancer_type: ACC, method: kewltm, task: n
84 32
cancer_type: ACC, method: kewltm, task: t
84 84
cancer_type: ACC, method: kewrag, task: n
88 66
cancer_type: ACC, method: kewrag, task: t
88 86
cancer_type: ACC, method: rag, task: n
88 67
cancer_type: ACC, method: rag, task: t
88 87
cancer_type: ACC, method: zscot, task: n
88 83
cancer_type: ACC, method: zscot, task: t
88 87
cancer_type: BLCA, method: kewltm, task: n
321 320
cancer_type: BLCA, method: kewltm, task: t
328 326
cancer_type: BLCA, method: kewrag, task: n
338 319
cancer_type: BLCA, method: kewrag, task: t
345 342
cancer_type: BLCA, method: rag, task: n
338 331
cancer_type: BLCA, method: rag, task: t
345 333
cancer_type: BLCA, method: zscot, task: n
338 335
cancer_type: BLCA, method: zscot, task: t
345 343
cancer_type: BRCA, method: kewltm, task: n
760 703
cancer_type: BRCA, method: kewltm, task: t
979 971
cancer_type: BRCA, method: kewrag, task: n
800 787
cancer_type: BRCA, method: kewrag, task: t
1031 1020
cancer_type: BRCA, method: rag, task: n
800 778
cancer_type: BRCA, method: rag, task: t
1031 1013
cancer_type: BRCA, method: zscot, task: n
800 792
cancer_type: BRCA, method: zscot, task: t
1031 1025
cancer_type: CESC, method: kewltm, task: n
175 172
cancer_type: CESC, method: kewltm, task: t
216 206
cancer_type: CESC, method: kewrag, task: n
184 184
cancer_type: CESC, method: kewrag, task: t
227 214
cancer_type: CESC, method: rag, task: n
184 182
cancer_type: CESC, method: rag, task: t
227 215
cancer_type: CESC, method: zscot, task: n
184 178
cancer_type: CESC, method: zscot, task: t
227 214
cancer_type: CHOL, method: kewltm, task: n
36 35
cancer_type: CHOL, method: kewltm, task: t
41 41
cancer_type: CHOL, method: kewrag, task: n
38 35
cancer_type: CHOL, method: kewrag, task: t
43 43
cancer_type: CHOL, method: rag, task: n
38 35
cancer_type: CHOL, method: rag, task: t
43 42
cancer_type: CHOL, method: zscot, task: n
38 38
cancer_type: CHOL, method: zscot, task: t
43 43
cancer_type: COAD, method: kewltm, task: n
397 394
cancer_type: COAD, method: kewltm, task: t
396 394
cancer_type: COAD, method: kewrag, task: n
418 413
cancer_type: COAD, method: kewrag, task: t
417 412
cancer_type: COAD, method: rag, task: n
418 411
cancer_type: COAD, method: rag, task: t
417 403
cancer_type: COAD, method: zscot, task: n
418 416
cancer_type: COAD, method: zscot, task: t
417 403
cancer_type: ESCA, method: kewltm, task: n
122 119
cancer_type: ESCA, method: kewltm, task: t
123 121
cancer_type: ESCA, method: kewrag, task: n
128 123
cancer_type: ESCA, method: kewrag, task: t
129 126
cancer_type: ESCA, method: rag, task: n
128 124
cancer_type: ESCA, method: rag, task: t
129 117
cancer_type: ESCA, method: zscot, task: n
128 127
cancer_type: ESCA, method: zscot, task: t
129 125
cancer_type: HNSC, method: kewltm, task: n
399 392
cancer_type: HNSC, method: kewltm, task: t
434 430
cancer_type: HNSC, method: kewrag, task: n
420 404
cancer_type: HNSC, method: kewrag, task: t
457 447
cancer_type: HNSC, method: rag, task: n
420 400
cancer_type: HNSC, method: rag, task: t
457 419
cancer_type: HNSC, method: zscot, task: n
420 405
cancer_type: HNSC, method: zscot, task: t
457 442
cancer_type: KICH, method: kewltm, task: n
50 43
cancer_type: KICH, method: kewltm, task: t
106 101
cancer_type: KICH, method: kewrag, task: n
53 53
cancer_type: KICH, method: kewrag, task: t
112 110
cancer_type: KICH, method: rag, task: n
53 42
cancer_type: KICH, method: rag, task: t
112 104
cancer_type: KICH, method: zscot, task: n
53 52
cancer_type: KICH, method: zscot, task: t
112 110
cancer_type: KIRC, method: kewltm, task: n
238 223
cancer_type: KIRC, method: kewltm, task: t
499 496
cancer_type: KIRC, method: kewrag, task: n
251 221
cancer_type: KIRC, method: kewrag, task: t
525 520
cancer_type: KIRC, method: rag, task: n
251 178
cancer_type: KIRC, method: rag, task: t
525 496
cancer_type: KIRC, method: zscot, task: n
251 235
cancer_type: KIRC, method: zscot, task: t
525 508
cancer_type: KIRP, method: kewltm, task: n
70 69
cancer_type: KIRP, method: kewltm, task: t
266 264
cancer_type: KIRP, method: kewrag, task: n
74 71
cancer_type: KIRP, method: kewrag, task: t
280 277
cancer_type: KIRP, method: rag, task: n
74 63
cancer_type: KIRP, method: rag, task: t
280 263
cancer_type: KIRP, method: zscot, task: n
74 71
cancer_type: KIRP, method: zscot, task: t
280 274
cancer_type: LIHC, method: kewltm, task: n
217 82
cancer_type: LIHC, method: kewltm, task: t
322 309
cancer_type: LIHC, method: kewrag, task: n
228 211
cancer_type: LIHC, method: kewrag, task: t
339 333
cancer_type: LIHC, method: rag, task: n
228 155
cancer_type: LIHC, method: rag, task: t
339 318
cancer_type: LIHC, method: zscot, task: n
228 217
cancer_type: LIHC, method: zscot, task: t
339 329
cancer_type: LUAD, method: kewltm, task: n
453 443
cancer_type: LUAD, method: kewltm, task: t
462 456
cancer_type: LUAD, method: kewrag, task: n
477 474
cancer_type: LUAD, method: kewrag, task: t
486 480
cancer_type: LUAD, method: rag, task: n
477 448
cancer_type: LUAD, method: rag, task: t
486 444
cancer_type: LUAD, method: zscot, task: n
477 443
cancer_type: LUAD, method: zscot, task: t
486 471
cancer_type: LUSC, method: kewltm, task: n
439 424
cancer_type: LUSC, method: kewltm, task: t
445 440
cancer_type: LUSC, method: kewrag, task: n
462 447
cancer_type: LUSC, method: kewrag, task: t
468 457
cancer_type: LUSC, method: rag, task: n
462 430
cancer_type: LUSC, method: rag, task: t
468 453
cancer_type: LUSC, method: zscot, task: n
462 435
cancer_type: LUSC, method: zscot, task: t
468 458
cancer_type: MESO, method: kewltm, task: n
71 43
cancer_type: MESO, method: kewltm, task: t
74 70
cancer_type: MESO, method: kewrag, task: n
75 70
cancer_type: MESO, method: kewrag, task: t
78 73
cancer_type: MESO, method: rag, task: n
75 67
cancer_type: MESO, method: rag, task: t
78 70
cancer_type: MESO, method: zscot, task: n
75 69
cancer_type: MESO, method: zscot, task: t
78 74
cancer_type: PAAD, method: kewltm, task: n
162 161
cancer_type: PAAD, method: kewltm, task: t
165 165
cancer_type: PAAD, method: kewrag, task: n
171 167
cancer_type: PAAD, method: kewrag, task: t
174 172
cancer_type: PAAD, method: rag, task: n
171 141
cancer_type: PAAD, method: rag, task: t
174 165
cancer_type: PAAD, method: zscot, task: n
171 169
cancer_type: PAAD, method: zscot, task: t
174 169
cancer_type: PRAD, method: kewltm, task: n
359 357
cancer_type: PRAD, method: kewltm, task: t
417 412
cancer_type: PRAD, method: kewrag, task: n
378 374
cancer_type: PRAD, method: kewrag, task: t
439 430
cancer_type: PRAD, method: rag, task: n
378 342
cancer_type: PRAD, method: rag, task: t
439 398
cancer_type: PRAD, method: zscot, task: n
378 370
cancer_type: PRAD, method: zscot, task: t
439 421
cancer_type: READ, method: kewltm, task: n
152 152
cancer_type: READ, method: kewltm, task: t
154 150
cancer_type: READ, method: kewrag, task: n
160 157
cancer_type: READ, method: kewrag, task: t
162 141
cancer_type: READ, method: rag, task: n
160 147
cancer_type: READ, method: rag, task: t
162 150
cancer_type: READ, method: zscot, task: n
160 156
cancer_type: READ, method: zscot, task: t
162 157
cancer_type: SKCM, method: kewltm, task: n
82 81
cancer_type: SKCM, method: kewltm, task: t
95 93
cancer_type: SKCM, method: kewrag, task: n
86 85
cancer_type: SKCM, method: kewrag, task: t
100 99
cancer_type: SKCM, method: rag, task: n
86 69
cancer_type: SKCM, method: rag, task: t
100 90
cancer_type: SKCM, method: zscot, task: n
86 83
cancer_type: SKCM, method: zscot, task: t
100 93
cancer_type: STAD, method: kewltm, task: n
326 325
cancer_type: STAD, method: kewltm, task: t
333 331
cancer_type: STAD, method: kewrag, task: n
343 340
cancer_type: STAD, method: kewrag, task: t
351 337
cancer_type: STAD, method: rag, task: n
343 319
cancer_type: STAD, method: rag, task: t
351 323
cancer_type: STAD, method: zscot, task: n
343 341
cancer_type: STAD, method: zscot, task: t
351 340
cancer_type: TGCT, method: kewltm, task: n
30 28
cancer_type: TGCT, method: kewltm, task: t
82 81
cancer_type: TGCT, method: kewrag, task: n
32 31
cancer_type: TGCT, method: kewrag, task: t
86 84
cancer_type: TGCT, method: rag, task: n
32 27
cancer_type: TGCT, method: rag, task: t
86 76
cancer_type: TGCT, method: zscot, task: n
32 31
cancer_type: TGCT, method: zscot, task: t
86 85
cancer_type: THCA, method: kewltm, task: n
415 404
cancer_type: THCA, method: kewltm, task: t
461 457
cancer_type: THCA, method: kewrag, task: n
437 407
cancer_type: THCA, method: kewrag, task: t
485 482
cancer_type: THCA, method: rag, task: n
437 408
cancer_type: THCA, method: rag, task: t
485 468
cancer_type: THCA, method: zscot, task: n
437 425
cancer_type: THCA, method: zscot, task: t
485 478
cancer_type: UVM, method: kewltm, task: n
35 35
cancer_type: UVM, method: kewltm, task: t
62 61
cancer_type: UVM, method: kewrag, task: n
37 35
cancer_type: UVM, method: kewrag, task: t
65 64
cancer_type: UVM, method: rag, task: n
37 26
cancer_type: UVM, method: rag, task: t
65 64
cancer_type: UVM, method: zscot, task: n
37 37
cancer_type: UVM, method: zscot, task: t
65 65

In [6]:
true_col

0     3.0
1     1.0
2     2.0
3     3.0
4     3.0
     ...
60    2.0
61    3.0
62    2.0
63    2.0
64    3.0
Name: T14, Length: 65, dtype: float64

In [7]:
import pandas as pd
df = pd.read_csv("/home/yl3427/cylab/selfCorrectionAgent/runs2/CESC_T14N03__kewltm__t__mistralai_Mixtral-8x7B-Instruct-v0.1__seed42__20250908_051211.csv")
df[~df["is_train"]]

FileNotFoundError: [Errno 2] No such file or directory: '/home/yl3427/cylab/selfCorrectionAgent/runs2/CESC_T14N03__kewltm__t__mistralai_Mixtral-8x7B-Instruct-v0.1__seed42__20250908_051211.csv'

In [ ]:
print(df[df["kewrag_stage"].isnull()].kewrag_reasoning.values[0])

To determine the N stage of the Adrenocortical Carcinoma cancer patient, we will follow the AJCC Cancer Staging Manual (7th edition) N staging rules provided.

1. Review the pathology report to locate information about regional lymph nodes.
2. Assess if the regional lymph nodes can be assessed (pNX), if there is no regional lymph node metastasis (pN0), or if there is metastasis in regional lymph nodes (pN1, pN2, or pN3).

Step 1: Analyzing the pathology report
The pathology report includes information about the adrenal tumor, IVC invasive mass, and additional tumor from the crus of the right diaphragm. However, there is no explicit mention of regional lymph nodes or their metastasis.

Step 2: Staging the patient
Since the pathology report does not provide enough information about the regional lymph nodes, we cannot determine whether the lymph nodes were assessed (pNX), had no metastasis (pN0), or had metastasis (pN1, pN2, or pN3). Therefore, we cannot accurately assign an N stage based on the given information.

Final prediction: The N stage cannot be predicted without further information ({{

In [ ]:
df

,type,case_submitter_id,patient_filename,ajcc_pathologic_t,T14,ajcc_pathologic_n,N03,text,kewrag_rules,kewrag_reasoning,kewrag_stage
0,ACC,TCGA-OR-A5J1,TCGA-OR-A5J1.8866FD87-4F6F-4D7E-B99A-7DD427ED3BB3,T2,1.0,N0,0.0,Deliver To: NOS P. Cuncertain inknown behavior...,['NX: Regional lymph nodes cannot be assessed'...,"To determine the N stage for this patient, we ...",N0
1,ACC,TCGA-OR-A5J2,TCGA-OR-A5J2.345C34EE-F031-41A4-B955-BA054F2A3CE1,T3,2.0,N0,0.0,Date of Birth: Sex: Female. Macroscopy. Two ve...,['NX: Regional lymph nodes cannot be assessed'...,1. The pathology report provides information a...,NX
2,ACC,TCGA-OR-A5J3,TCGA-OR-A5J3.83F53610-4F40-425B-9B69-BBB94234224F,T3,2.0,N0,0.0,Sex: Female. Macroscopy. One vessel containing...,['NX: Regional lymph nodes cannot be assessed'...,The pathology report provides information abou...,N0
3,ACC,TCGA-OR-A5J4,TCGA-OR-A5J4.39E300DC-C01F-46BC-AE4C-D834458F1FF7,T3,2.0,N1,1.0,Sex: Female. Macroscopy. One vessel containing...,['NX: Regional lymph nodes cannot be assessed'...,1. The pathology report does not mention any e...,N0
4,ACC,TCGA-OR-A5J5,TCGA-OR-A5J5.BB63299C-B7F7-4F08-998D-C30E56CD6065,T4,3.0,N0,0.0,Sex: Male. Macroscopy. One vessel containing a...,['NX: Regional lymph nodes cannot be assessed'...,To determine the N stage for this patient usin...,NX
5,ACC,TCGA-OR-A5J6,TCGA-OR-A5J6.F664D25E-9050-460D-AEAE-AA4BFA515453,T2,1.0,N0,0.0,Sex: Female. Macroscopy. Two vessel containing...,['NX: Regional lymph nodes cannot be assessed'...,To determine the N stage for this patient with...,NX
6,ACC,TCGA-OR-A5J7,TCGA-OR-A5J7.F9C1971C-5BE2-4722-9A6C-CF4A4AD04352,T3,2.0,N0,0.0,Sex: Female. Macroscopy. Two vessels containin...,['NX: Regional lymph nodes cannot be assessed'...,The pathology report provides information abou...,NX
7,ACC,TCGA-OR-A5J8,TCGA-OR-A5J8.EA68CD7A-9308-40CD-BB52-CEB36334A146,T3,2.0,N0,0.0,Sex: Male. Macroscopy. One vessel containing a...,['NX: Regional lymph nodes cannot be assessed'...,To determine the N stage for this patient with...,NX
8,ACC,TCGA-OR-A5J9,TCGA-OR-A5J9.4C775CF4-39D7-4246-87A4-4659783A1C18,T2,1.0,N0,0.0,Sex: Female. Macroscopy. One vessel containing...,['NX: Regional lymph nodes cannot be assessed'...,In order to determine the N stage for this pat...,NX - Regional lymph nodes cannot be assessed
9,ACC,TCGA-OR-A5JA,TCGA-OR-A5JA.6A505565-429B-4D8A-A591-AAB54CF43B66,T4,3.0,N0,0.0,Requesting Doctor's information: HISTOPATHOLOG...,['NX: Regional lymph nodes cannot be assessed'...,To determine the N stage of the Adrenocortical...,NaN

In [ ]:
df2 = pd.read_csv("/home/yl3427/cylab/selfCorrectionAgent/runs2/ACC_T14N03__zscot__n__mistralai_Mixtral-8x7B-Instruct-v0.1__seed42__20250908_041406.csv")
print(df2.iloc[9].zscot_reasoning)

The N stage for Adrenocortical Carcinoma is determined by the presence and extent of regional lymph node metastasis. According to the AJCC Cancer Staging Manual (7th edition), N category is defined as follows:

NX: Regional lymph nodes cannot be assessed.
N0: No regional lymph node metastasis.
N1: Metastasis in regional lymph node(s).

In this pathology report, there is no mention of any lymph node evaluation or metastasis. The report describes the primary tumor in the right adrenal gland, an IVC invasive mass, and additional tumors in the crus of the right diaphragm, but there is no information about regional lymph nodes. Therefore,

The N stage for this Adrenocortical Carcinoma is NX, as the regional lymph nodes cannot be assessed from the provided information.

However, since NX is not a valid option in the provided choices, I would select N0, assuming that there is no evidence of regional lymph node metastasis based on the given report.

In [ ]:
from pathlib import Path  
import pandas as pd

csv_path = Path("/home/yl3427/cylab/selfCorrectionAgent/runs2").resolve().glob("*zscot*.csv")
for p in csv_path:
    print(p.name.split("_")[0], p.name.split("__")[2])
    df = pd.read_csv(p)
    print(len(df))
    print(df)

THCA n
10
KIRC n
6
KIRP t
10
COAD t
10
LIHC t
10
LUAD n
10
PAAD n
10
PAAD t
10
CESC n
10
LUSC n
10
PRAD n
8
BRCA t
10
ESCA t
10
ACC n
10
CHOL n
9
LUSC t
10
READ t
10
BRCA n
7
HNSC t
10
PRAD t
10
UVM t
10
TGCT n
10
SKCM t
10
THCA t
10
KICH n
7
ESCA n
10
STAD t
10
BLCA t
10
ACC t
10
UVM n
7
CESC t
9
MESO t
9
COAD n
10
SKCM n
10
LIHC n
2
READ n
10
LUAD t
10
KIRC t
10
BLCA n
9
KIRP n
1
KICH t
10
STAD n
7
TGCT t
10
MESO n
10
HNSC n
9
CHOL t
10

In [ ]:
df

,type,case_submitter_id,patient_filename,ajcc_pathologic_t,T14,ajcc_pathologic_n,N03,text,zscot_reasoning,zscot_stage
0,CHOL,TCGA-3X-AAV9,TCGA-3X-AAV9.3E7DD345-7A2C-4D7B-B5A2-2207949186CA,T1,0.0,N0,0.0,CONFIDENTIAL. Demographics (for. verification ...,The T stage for cholangiocarcinoma is determin...,T2
1,CHOL,TCGA-3X-AAVA,TCGA-3X-AAVA.4C9A220D-03E9-41CF-8FA9-4B7FD05A625A,T2b,1.0,NaN,NaN,CONFIDENTIAL. Demographics (for. verification ...,The T stage for cholangiocarcinoma is determin...,T2b
2,CHOL,TCGA-3X-AAVB,TCGA-3X-AAVB.BEA4C577-73ED-48F0-9417-AA8BD143B5C8,T3,2.0,N1,1.0,CONFIDENTIAL. Demographics (for. verification ...,The T stage for cholangiocarcinoma is determin...,T3
3,CHOL,TCGA-3X-AAVC,TCGA-3X-AAVC.88206A8B-257B-4C0F-B42C-905DEA9483FB,T1,0.0,N0,0.0,CONFIDENTIAL. Demographics (for. verification ...,The T stage for cholangiocarcinoma is based on...,T1b
4,CHOL,TCGA-4G-AAZF,TCGA-4G-AAZF.D67904F4-8D02-4D23-9390-C864A7B5344D,T3,2.0,N0,0.0,Anatomic site: intrahepatic. Histology diagnos...,To determine the T stage of cholangiocarcinoma...,T2
5,CHOL,TCGA-4G-AAZG,TCGA-4G-AAZG.4E32E573-17EA-49A4-A90F-A0830E3279C9,T3,2.0,N0,0.0,Anatomic site: intrahepatic. Histology diagnos...,To determine the T stage of cholangiocarcinoma...,T2
6,CHOL,TCGA-4G-AAZO,TCGA-4G-AAZO.C6A65949-C248-4729-B41F-9C65A46A7AF7,T2a,1.0,N0,0.0,Anatomic site: intrahepatic. Histology diagnos...,To determine the T stage of cholangiocarcinoma...,T2
7,CHOL,TCGA-4G-AAZR,TCGA-4G-AAZR.0411F033-20FA-4F8F-AD51-A4EDF3E758BE,T2a,1.0,N0,0.0,Anatomic site: perihilar. Histology diagnosis:...,The T stage for cholangiocarcinoma is determin...,T3
8,CHOL,TCGA-4G-AAZT,TCGA-4G-AAZT.C75C91FD-D4DE-4A58-A4C7-8F020AAC59EB,T1,0.0,N0,0.0,Anatomic site: intrahepatic. Histology diagnos...,To determine the T stage of cholangiocarcinoma...,T2
9,CHOL,TCGA-W5-AA2G,TCGA-W5-AA2G.1E7EDF0B-283F-44F9-A89A-83DB12A0D58A,T1,0.0,N0,0.0,"Female. Surgery Date: DIAGNOSIS: Liver, right ...",The T stage of cholangiocarcinoma is determine...,T2